version: '3.7'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  backend:
    image: leopetersberg/counterbackend:latest
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/`)"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      replicas: 2

  frontend:
    image: leopetersberg/counterfrontend:latest
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    depends_on:
      - backend
    deploy:
      replicas: 2

volumes:
  redis_data:
