version: '3.7'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    image: leopetersberg/counterbackend
    ports:
      - "800:800"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    image: leopetersberg/counterfrontend
    ports:
      - "3000:3000" # Nginx lauscht standardmäßig auf Port 80
    depends_on:
      - backend